# This workflow automatically posts a guidance comment on new pull requests.
# It welcomes contributors and provides a brief message to acknowledge their 
# contribution to the Simple WP Optimizer plugin.
# The workflow is triggered whenever a new pull request is opened.

name: New Pull Request Guidance

on:
  pull_request_target:
    types: [opened]

jobs:
  guide:
    runs-on: ubuntu-latest
    # Explicitly define permissions required by the job
    permissions:
      pull-requests: write
    steps:
      - name: Post guidance comment on new PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thanks for contributing to Simple WP Optimizer! 🎉


            We'll review your PR soon!
          # Token is implicitly provided with the defined permissions
          # token: ${{ secrets.GITHUB_TOKEN }} # This line can be removed